# Generated by Django 2.0 on 2018-03-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20180330_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
