# Generated by Django 2.0.2 on 2018-03-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20180311_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='votername', max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='roll',
            field=models.CharField(default='rollno', max_length=7),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
