# Generated by Django 2.0 on 2018-03-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20180330_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='ended',
            field=models.BooleanField(default=True),
        ),
    ]
