# Generated by Django 2.0.1 on 2018-03-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20180311_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='candidatename', max_length=30),
        ),
    ]
