# Generated by Django 2.0.1 on 2018-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_auto_20180312_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/6/67/User_Avatar.png', upload_to=''),
        ),
    ]
