# Generated by Django 2.0.1 on 2018-03-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_candidate_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar',
            field=models.CharField(default='Url of the image', max_length=1000),
        ),
    ]
