# Generated by Django 2.0.1 on 2018-03-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20180314_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar',
            field=models.FileField(upload_to=''),
        ),
    ]
