# Generated by Django 2.0.2 on 2018-03-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20180315_0618'),
        ('election', '0010_auto_20180315_1636'),
    ]

    operations = [
    ]
