# Generated by Django 2.0.2 on 2018-03-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_merge_20180315_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='voter',
            name='avatar',
        ),
    ]
