# Generated by Django 2.0.2 on 2018-03-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_auto_20180315_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
