# Generated by Django 2.0 on 2018-03-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_auto_20180316_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='avatar',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/6/67/User_Avatar.png', upload_to=''),
        ),
    ]
